// This file is auto-generated by wrangler, but we define it manually here.
// It describes the Env interface which is available in the worker context.

interface Env {
  // ---- Mock Flags ----
  USE_MOCK_LINE: string;
  USE_MOCK_AI: string;
  USE_MOCK_STORAGE: string;
  USE_MOCK_AUTH: string;

  // ---- LINE Messaging API ----
  LINE_CHANNEL_SECRET: string;
  LINE_CHANNEL_ACCESS_TOKEN: string;

  // ---- カード利用速報メール通知 ----
  // 通知先の LINE グループ ID（secret）
  LINE_NOTIFY_GROUP_ID: string;
  // /notify/card-email の共有ベアラトークン（secret）
  CARD_EMAIL_WEBHOOK_TOKEN: string;

  // ---- LINE Login OAuth ----
  LINE_LOGIN_CHANNEL_ID: string;
  LINE_LOGIN_CHANNEL_SECRET: string;
  LINE_LOGIN_CALLBACK_URL: string;
  JWT_SECRET: string;

  // ---- Gemini API ----
  GEMINI_API_KEY: string;
  GEMINI_MODEL?: string;

  // ---- Google Sheets API ----
  GOOGLE_SERVICE_ACCOUNT_EMAIL: string;
  GOOGLE_PRIVATE_KEY: string;
  SPREADSHEET_ID: string;

  // ---- アプリ設定 ----
  APP_BASE_URL: string;
}
