// This file is auto-generated by wrangler, but we define it manually here.
// It describes the Env interface which is available in the worker context.

interface Env {
  // ---- Mock Flags ----
  USE_MOCK_LINE: string;
  USE_MOCK_AI: string;
  USE_MOCK_STORAGE: string;
  USE_MOCK_LIFF: string;

  // ---- LINE Messaging API ----
  LINE_CHANNEL_SECRET: string;
  LINE_CHANNEL_ACCESS_TOKEN: string;

  // ---- LIFF ----
  LIFF_ID: string;

  // ---- Gemini API ----
  GEMINI_API_KEY: string;
  GEMINI_MODEL?: string;

  // ---- Google Sheets API ----
  GOOGLE_SERVICE_ACCOUNT_EMAIL: string;
  GOOGLE_PRIVATE_KEY: string;
  SPREADSHEET_ID: string;
}
